### ISSUE TITLE
Web Panel session not opening

### ISSUE THREAD

**Issue by medusanew100** [brownlucky3860/phislets#1]
Here is what I'm getting on after node app.js 
express-session deprecated req.secret; provide secret option app.js:35:9
Server Running on Port 4000...
I typed d IP:port but not working
![Screen Shot 2023-02-13 at 2 11 13 AM](https://user-images.githubusercontent.com/113239904/218393914-90a7fa54-5736-4a99-8811-74ea99689079.png)

**Comment by medusanew100** [comment]
express-session deprecated req.secret; provide secret option app.js:35:9
Server Running on Port 4000...
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (/root/.evilginx/Web-Panel-Evilginx/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/root/.evilginx/Web-Panel-Evilginx/app.js:94:5)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1767:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 4000
}
 Please any help?

**Comment by ghost** [comment]
fixed
